"use client"

import { useState, useEffect } from 'react'
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog"
import { Badge } from "@/components/ui/badge"
import { 
  Package, 
  MapPin, 
  Warehouse, 
  Store, 
  Building, 
  Plus, 
  Edit, 
  Trash2, 
  PackageCheck, 
  PackagePlus,
  PackageMinus
} from "lucide-react"
import { InventoryLocation } from '@/lib/types'

interface InventoryLocationManagerProps {
  vendorId: string
  locations: InventoryLocation[]
  onLocationsChange?: (locations: InventoryLocation[]) => void
}

export function InventoryLocationManager({ 
  vendorId, 
  locations, 
  onLocationsChange 
}: InventoryLocationManagerProps) {
  const [isDialogOpen, setIsDialogOpen] = useState(false)
  const [editingLocation, setEditingLocation] = useState<InventoryLocation | null>(null)
  const [formData, setFormData] = useState<Omit<InventoryLocation, 'id' | 'vendor_id' | 'created_at' | 'updated_at'>>({
    name: '',
    type: 'warehouse',
    address: '',
    city: '',
    state: '',
    postal_code: '',
    country: 'US',
    is_active: true,
    is_pickup_location: false,
    is_shipping_origin: true,
  })

  useEffect(() => {
    if (editingLocation) {
      setFormData({
        name: editingLocation.name,
        type: editingLocation.type,
        address: editingLocation.address,
        city: editingLocation.city,
        state: editingLocation.state,
        postal_code: editingLocation.postal_code,
        country: editingLocation.country,
        is_active: editingLocation.is_active,
        is_pickup_location: editingLocation.is_pickup_location,
        is_shipping_origin: editingLocation.is_shipping_origin,
      })
    } else {
      resetForm()
    }
  }, [editingLocation])

  const resetForm = () => {
    setFormData({
      name: '',
      type: 'warehouse',
      address: '',
      city: '',
      state: '',
      postal_code: '',
      country: 'US',
      is_active: true,
      is_pickup_location: false,
      is_shipping_origin: true,
    })
  }

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value, type, checked } = e.target
    setFormData(prev => ({
      ...prev,
      [name]: type === 'checkbox' ? checked : value
    }))
  }

  const handleSelectChange = (name: string, value: string) => {
    setFormData(prev => ({
      ...prev,
      [name]: value
    }))
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    
    try {
      let updatedLocations: InventoryLocation[]
      
      if (editingLocation) {
        // Update existing location
        updatedLocations = locations.map(loc => 
          loc.id === editingLocation.id ? { ...loc, ...formData } : loc
        )
      } else {
        // Create new location
        const newLocation: InventoryLocation = {
          id: `loc_${Date.now()}`, // In real app, this would be generated by the server
          vendor_id: vendorId,
          ...formData,
          created_at: new Date().toISOString(),
          updated_at: new Date().toISOString()
        }
        updatedLocations = [...locations, newLocation]
      }
      
      if (onLocationsChange) {
        onLocationsChange(updatedLocations)
      }
      setIsDialogOpen(false)
      resetForm()
    } catch (error) {
      console.error('Error saving location:', error)
    }
  }

  const handleDelete = (id: string) => {
    if (window.confirm('Are you sure you want to delete this location?')) {
      const updatedLocations = locations.filter(loc => loc.id !== id)
      if (onLocationsChange) {
        onLocationsChange(updatedLocations)
      }
    }
  }

  const getLocationIcon = (type: string) => {
    switch (type) {
      case 'warehouse': return <Warehouse className="h-4 w-4" />
      case 'store': return <Store className="h-4 w-4" />
      case 'distribution_center': return <Building className="h-4 w-4" />
      default: return <MapPin className="h-4 w-4" />
    }
  }

  const getLocationBadgeVariant = (type: string) => {
    switch (type) {
      case 'warehouse': return 'bg-blue-100 text-blue-800'
      case 'store': return 'bg-green-100 text-green-800'
      case 'distribution_center': return 'bg-purple-100 text-purple-800'
      default: return 'bg-gray-100 text-gray-800'
    }
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <Package className="h-5 w-5" />
          Inventory Locations
        </CardTitle>
        <CardDescription>
          Manage your warehouses, stores, and distribution centers
        </CardDescription>
      </CardHeader>
      <CardContent>
        <div className="flex justify-between items-center mb-4">
          <h3 className="text-lg font-medium">Locations</h3>
          <Dialog open={isDialogOpen} onOpenChange={setIsDialogOpen}>
            <DialogTrigger asChild>
              <Button 
                onClick={() => {
                  setEditingLocation(null)
                  resetForm()
                }}
              >
                <Plus className="h-4 w-4 mr-2" />
                Add Location
              </Button>
            </DialogTrigger>
            <DialogContent>
              <DialogHeader>
                <DialogTitle>
                  {editingLocation ? 'Edit Location' : 'Add New Location'}
                </DialogTitle>
                <DialogDescription>
                  {editingLocation 
                    ? 'Update the details of your inventory location' 
                    : 'Add a new warehouse, store, or distribution center'}
                </DialogDescription>
              </DialogHeader>
              <form onSubmit={handleSubmit} className="space-y-4">
                <div className="space-y-2">
                  <Label htmlFor="name">Location Name</Label>
                  <Input
                    id="name"
                    name="name"
                    value={formData.name}
                    onChange={handleInputChange}
                    required
                  />
                </div>
                
                <div className="space-y-2">
                  <Label htmlFor="type">Location Type</Label>
                  <Select 
                    value={formData.type} 
                    onValueChange={(value) => handleSelectChange('type', value)}
                  >
                    <SelectTrigger>
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="warehouse">Warehouse</SelectItem>
                      <SelectItem value="store">Store</SelectItem>
                      <SelectItem value="distribution_center">Distribution Center</SelectItem>
                      <SelectItem value="custom">Custom</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
                
                <div className="space-y-2">
                  <Label htmlFor="address">Address</Label>
                  <Input
                    id="address"
                    name="address"
                    value={formData.address}
                    onChange={handleInputChange}
                    required
                  />
                </div>
                
                <div className="grid grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label htmlFor="city">City</Label>
                    <Input
                      id="city"
                      name="city"
                      value={formData.city}
                      onChange={handleInputChange}
                      required
                    />
                  </div>
                  
                  <div className="space-y-2">
                    <Label htmlFor="state">State</Label>
                    <Input
                      id="state"
                      name="state"
                      value={formData.state}
                      onChange={handleInputChange}
                      required
                    />
                  </div>
                </div>
                
                <div className="grid grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label htmlFor="postal_code">Postal Code</Label>
                    <Input
                      id="postal_code"
                      name="postal_code"
                      value={formData.postal_code}
                      onChange={handleInputChange}
                      required
                    />
                  </div>
                  
                  <div className="space-y-2">
                    <Label htmlFor="country">Country</Label>
                    <Input
                      id="country"
                      name="country"
                      value={formData.country}
                      onChange={handleInputChange}
                      required
                    />
                  </div>
                </div>
                
                <div className="flex items-center space-x-2">
                  <input
                    type="checkbox"
                    id="is_active"
                    name="is_active"
                    checked={formData.is_active}
                    onChange={handleInputChange}
                    className="h-4 w-4"
                  />
                  <Label htmlFor="is_active">Active Location</Label>
                </div>
                
                <div className="flex items-center space-x-2">
                  <input
                    type="checkbox"
                    id="is_pickup_location"
                    name="is_pickup_location"
                    checked={formData.is_pickup_location}
                    onChange={handleInputChange}
                    className="h-4 w-4"
                  />
                  <Label htmlFor="is_pickup_location">Available for BOPIS (Buy Online, Pick Up In Store)</Label>
                </div>
                
                <div className="flex items-center space-x-2">
                  <input
                    type="checkbox"
                    id="is_shipping_origin"
                    name="is_shipping_origin"
                    checked={formData.is_shipping_origin}
                    onChange={handleInputChange}
                    className="h-4 w-4"
                  />
                  <Label htmlFor="is_shipping_origin">Available for Shipping</Label>
                </div>
                
                <div className="flex justify-end space-x-2 pt-4">
                  <Button 
                    type="button" 
                    variant="outline" 
                    onClick={() => setIsDialogOpen(false)}
                  >
                    Cancel
                  </Button>
                  <Button type="submit">
                    {editingLocation ? 'Update' : 'Create'} Location
                  </Button>
                </div>
              </form>
            </DialogContent>
          </Dialog>
        </div>
        
        {locations.length === 0 ? (
          <div className="text-center py-8 text-muted-foreground">
            <Package className="h-12 w-12 mx-auto mb-2" />
            <p>No inventory locations configured yet</p>
            <p className="text-sm">Add your first warehouse, store, or distribution center</p>
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {locations.map((location) => (
              <div 
                key={location.id} 
                className="border rounded-lg p-4 flex flex-col"
              >
                <div className="flex justify-between items-start">
                  <div className="flex items-center gap-2">
                    {getLocationIcon(location.type)}
                    <h4 className="font-medium">{location.name}</h4>
                  </div>
                  <div className="flex gap-1">
                    <Button
                      variant="ghost"
                      size="sm"
                      onClick={() => {
                        setEditingLocation(location)
                        setIsDialogOpen(true)
                      }}
                    >
                      <Edit className="h-4 w-4" />
                    </Button>
                    <Button
                      variant="ghost"
                      size="sm"
                      onClick={() => handleDelete(location.id)}
                    >
                      <Trash2 className="h-4 w-4" />
                    </Button>
                  </div>
                </div>
                
                <div className="mt-2">
                  <Badge className={getLocationBadgeVariant(location.type)}>
                    {location.type.replace('_', ' ')}
                  </Badge>
                </div>
                
                <div className="mt-3 text-sm text-muted-foreground space-y-1">
                  <p>{location.address}</p>
                  <p>{location.city}, {location.state} {location.postal_code}</p>
                  <p>{location.country}</p>
                </div>
                
                <div className="mt-3 flex flex-wrap gap-2">
                  {location.is_pickup_location && (
                    <Badge variant="secondary" className="text-xs">
                      <PackageCheck className="h-3 w-3 mr-1" />
                      BOPIS
                    </Badge>
                  )}
                  {location.is_shipping_origin && (
                    <Badge variant="secondary" className="text-xs">
                      <PackagePlus className="h-3 w-3 mr-1" />
                      Shipping Origin
                    </Badge>
                  )}
                  {!location.is_active && (
                    <Badge variant="outline" className="text-xs border-red-500 text-red-500">
                      <PackageMinus className="h-3 w-3 mr-1" />
                      Inactive
                    </Badge>
                  )}
                </div>
              </div>
            ))}
          </div>
        )}
      </CardContent>
    </Card>
  )
}